# Generated by Django 4.0.3 on 2022-04-10 06:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_equipmentfamily_equipment_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipmenttype',
            name='family',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.equipmentfamily'),
        ),
    ]
