# Generated by Django 4.0.3 on 2022-04-10 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_equipmenttype_family'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipmentfamily',
            name='name',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
