# Generated by Django 4.0.3 on 2022-04-11 04:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_equipmentgroup_equipmentfamily_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipmentfamily',
            name='image',
            field=models.ImageField(default='test', upload_to='', verbose_name='Баннер'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='equipment',
            name='description',
            field=models.TextField(null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='label',
            field=models.CharField(max_length=300, verbose_name='Марка'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.equipmenttype', verbose_name='Тип'),
        ),
        migrations.AlterField(
            model_name='equipmentgroup',
            name='name',
            field=models.CharField(default='test', max_length=100),
            preserve_default=False,
        ),
    ]
