# Generated by Django 4.0.3 on 2022-04-16 04:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_alter_equipmentfamily_image'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='EquipmentType',
            new_name='EquipmentCategory',
        ),
    ]
