# Generated by Django 4.0.3 on 2022-04-23 05:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_alter_equipment_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название бренда')),
                ('image', models.ImageField(upload_to='', verbose_name='Логотип')),
            ],
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('star_count', models.IntegerField(default=0, verbose_name='Рейтинг')),
            ],
        ),
        migrations.AddField(
            model_name='equipment',
            name='in_stock',
            field=models.CharField(choices=[('Нет в наличии', 0), ('Осталось мало', 1), ('В наличии', 2), ('В наличии', 3)], default=0, max_length=100, verbose_name='Количество'),
        ),
        migrations.AddField(
            model_name='equipment',
            name='is_promo',
            field=models.BooleanField(default=False, verbose_name='Акционный'),
        ),
        migrations.AddField(
            model_name='equipment',
            name='brand',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='brand', to='shop.brand', verbose_name='Бренд'),
        ),
        migrations.AddField(
            model_name='equipment',
            name='rating',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rating', to='shop.rating', verbose_name='Рейтинг'),
        ),
    ]
